### ISSUE TITLE
Backend - reparar cors en backend para aceptar peticiones desde nuxt

### ISSUE THREAD

**Issue by motohrr** [motohrr/DenttalProFrontend#13]
Actualmente el servidor esta generando respuesta 200 pero retorna error de cors esto se debe a que no se envia el header de allow-cross-origin en el preflight de la respuesta del endpoint:

![Image](https://user-images.githubusercontent.com/42724495/194786042-ce56bea6-c7e7-441e-a0d6-bfa676c273b0.png)

Enlaces de referencia de la incidencia:
https://stackoverflow.com/questions/55629594/axios-get-method-having-network-error-and-cors-policy-with-status-code-200
https://github.com/axios/axios/issues/569

**Comment by luiscerna** [comment]
El proyecto se encuentra bien los cors, el problema se estaba ocasionando en el servidor publicado nginx ya que sirve de puente para recibir las peticiones a la api.
