### ISSUE TITLE
Backend - Refactor de endpoint para enviar/mensaje de confirmacion al email.

### ISSUE THREAD

**Issue by motohrr** [motohrr/DenttalProFrontend#20]
Modificar el endpoint de envio de correo de confirmacion para que acepte el siguiente payload como body:
`
{
     email: "correo_electronico@dominio.com"
}
`
Y que retorne el siguiente payload de respuesta:
`
{
    verificationCode: "006622"
}
`

**Comment by luiscerna** [comment]
Se ha cancelado porque se va a refactorizar el proceso de confirmación email.
